# .github/workflows/linux.yml
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Linux Build

on:
  push:
    branches: ["main"]
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"
      - "examples/**"
      - "cmake/**"
      - "Makefile"
      - "CMakePresets.json"
      - "CMakeLists.txt"
      - ".clang-tidy"
      - ".github/workflows/linux.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"
      - "examples/**"
      - "cmake/**"
      - "Makefile"
      - "CMakePresets.json"
      - "CMakeLists.txt"
      - ".clang-tidy"
      - ".github/workflows/linux.yml"

jobs:
  build:
    runs-on: ubuntu-24.04
    container: silkeh/clang:19
    strategy:
      fail-fast: false

      matrix:
        # TODO: sanitizer: [debug, release, asan, usan, tsan, lsan, msan]
        preset: [debug]
        compiler: [clang++-19]

    steps:
      - uses: actions/checkout@master
        with:
          path: task29

      - uses: actions/checkout@master
        with:
          repository: bemanproject/execution26
          path: execution26

      - name: Install dependencies
        run: |
          wget -q https://github.com/Kitware/CMake/releases/download/v3.31.3/cmake-3.31.3-linux-x86_64.sh && \
          chmod +x cmake-3.31.3-linux-x86_64.sh && \
          ./cmake-3.31.3-linux-x86_64.sh --skip-license --prefix=/usr

      - name: Install build tools
        run: |
          apt-get update -y -q
          apt-get install cppcheck ninja-build git -y -q

      - name: Linux task29 ${{ matrix.compiler }} ${{ matrix.preset }}
        run: |
          cd task29
          cmake --preset ${{ matrix.compiler }}-${{ matrix.preset }} .
          cmake --build build
          ctest --test-dir build --output-on-failure